version: '2'
services:
 mongodb:
   image: mongo
   restart: always
   container_name: mongodb1
   ports : 
   - 27018:27017
   volumes:
   - ./mongodb/data:/data/db 
 flask-service:
   image: image
   build:
     context: ./flask 
   restart: always 
   container_name: flask 
   depends_on: 
   - mongodb
   ports:
   - 5000:5000
   environment: 
   - "MONGO_HOSTNAME=mongodb"         
